version: '2.4'

services:
  # mongo
  mongo:
    image: 'mongo:4.4'
    hostname: mongo
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - vol_mongo_data:/data/db
    networks: 
      - net_api
  # api
  api:
    build: .
    hostname: api
    env_file: ./api/.env
    environment: 
      - SERVER=mongodb://mongo
      - DB=api_db
    ports: 
      - 32323:32323
    networks: 
      - net_api

networks:
  net_api:
    name: net_api
    driver: bridge

volumes:
  vol_mongo_data: